import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Hero from '../components/Hero'
import Search from '../components/Search'
import Features from '../components/Features'
import FeaturedArtists from '../components/FeaturedArtists'
import ForYou from '../components/ForYou'
import Add from '../components/Add'
import GoToTopButton from '../components/GoToTopButton'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>ARTICUE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={'scroll-smooth'}>
          <Hero/>
          <Features/>
          <FeaturedArtists/>
          <ForYou/>
          <div id={'add'}>
              <Add/>
          </div>
          <div className="fixed bottom-4 right-4 z-30">
              <GoToTopButton/>
          </div>
      </main>
    </>
  )
}
